/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compaction-coordinator.proto

// Protobuf Java Version: 3.25.3
package org.apache.accumulo.grpc.compaction.protobuf;

/**
 * Protobuf type {@code compaction_coordinator.PCompactionStatusUpdate}
 */
public final class PCompactionStatusUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:compaction_coordinator.PCompactionStatusUpdate)
    PCompactionStatusUpdateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PCompactionStatusUpdate.newBuilder() to construct.
  private PCompactionStatusUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PCompactionStatusUpdate() {
    state_ = 0;
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PCompactionStatusUpdate();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.apache.accumulo.grpc.compaction.protobuf.CompactionCoordinatorServiceProto.internal_static_compaction_coordinator_PCompactionStatusUpdate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.apache.accumulo.grpc.compaction.protobuf.CompactionCoordinatorServiceProto.internal_static_compaction_coordinator_PCompactionStatusUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.class, org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.Builder.class);
  }

  public static final int STATE_FIELD_NUMBER = 1;
  private int state_ = 0;
  /**
   * <code>.compaction_coordinator.PCompactionState state = 1;</code>
   * @return The enum numeric value on the wire for state.
   */
  @java.lang.Override public int getStateValue() {
    return state_;
  }
  /**
   * <code>.compaction_coordinator.PCompactionState state = 1;</code>
   * @return The state.
   */
  @java.lang.Override public org.apache.accumulo.grpc.compaction.protobuf.PCompactionState getState() {
    org.apache.accumulo.grpc.compaction.protobuf.PCompactionState result = org.apache.accumulo.grpc.compaction.protobuf.PCompactionState.forNumber(state_);
    return result == null ? org.apache.accumulo.grpc.compaction.protobuf.PCompactionState.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTRIESTOBECOMPACTED_FIELD_NUMBER = 3;
  private long entriesToBeCompacted_ = 0L;
  /**
   * <code>int64 entriesToBeCompacted = 3;</code>
   * @return The entriesToBeCompacted.
   */
  @java.lang.Override
  public long getEntriesToBeCompacted() {
    return entriesToBeCompacted_;
  }

  public static final int ENTRIESREAD_FIELD_NUMBER = 4;
  private long entriesRead_ = 0L;
  /**
   * <code>int64 entriesRead = 4;</code>
   * @return The entriesRead.
   */
  @java.lang.Override
  public long getEntriesRead() {
    return entriesRead_;
  }

  public static final int ENTRIESWRITTEN_FIELD_NUMBER = 5;
  private long entriesWritten_ = 0L;
  /**
   * <code>int64 entriesWritten = 5;</code>
   * @return The entriesWritten.
   */
  @java.lang.Override
  public long getEntriesWritten() {
    return entriesWritten_;
  }

  public static final int COMPACTIONAGENANOS_FIELD_NUMBER = 6;
  private long compactionAgeNanos_ = 0L;
  /**
   * <code>int64 compactionAgeNanos = 6;</code>
   * @return The compactionAgeNanos.
   */
  @java.lang.Override
  public long getCompactionAgeNanos() {
    return compactionAgeNanos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (state_ != org.apache.accumulo.grpc.compaction.protobuf.PCompactionState.ASSIGNED.getNumber()) {
      output.writeEnum(1, state_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (entriesToBeCompacted_ != 0L) {
      output.writeInt64(3, entriesToBeCompacted_);
    }
    if (entriesRead_ != 0L) {
      output.writeInt64(4, entriesRead_);
    }
    if (entriesWritten_ != 0L) {
      output.writeInt64(5, entriesWritten_);
    }
    if (compactionAgeNanos_ != 0L) {
      output.writeInt64(6, compactionAgeNanos_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (state_ != org.apache.accumulo.grpc.compaction.protobuf.PCompactionState.ASSIGNED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, state_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (entriesToBeCompacted_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, entriesToBeCompacted_);
    }
    if (entriesRead_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, entriesRead_);
    }
    if (entriesWritten_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, entriesWritten_);
    }
    if (compactionAgeNanos_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, compactionAgeNanos_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate)) {
      return super.equals(obj);
    }
    org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate other = (org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate) obj;

    if (state_ != other.state_) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (getEntriesToBeCompacted()
        != other.getEntriesToBeCompacted()) return false;
    if (getEntriesRead()
        != other.getEntriesRead()) return false;
    if (getEntriesWritten()
        != other.getEntriesWritten()) return false;
    if (getCompactionAgeNanos()
        != other.getCompactionAgeNanos()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATE_FIELD_NUMBER;
    hash = (53 * hash) + state_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + ENTRIESTOBECOMPACTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntriesToBeCompacted());
    hash = (37 * hash) + ENTRIESREAD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntriesRead());
    hash = (37 * hash) + ENTRIESWRITTEN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntriesWritten());
    hash = (37 * hash) + COMPACTIONAGENANOS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCompactionAgeNanos());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code compaction_coordinator.PCompactionStatusUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:compaction_coordinator.PCompactionStatusUpdate)
      org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.accumulo.grpc.compaction.protobuf.CompactionCoordinatorServiceProto.internal_static_compaction_coordinator_PCompactionStatusUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.accumulo.grpc.compaction.protobuf.CompactionCoordinatorServiceProto.internal_static_compaction_coordinator_PCompactionStatusUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.class, org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.Builder.class);
    }

    // Construct using org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      state_ = 0;
      message_ = "";
      entriesToBeCompacted_ = 0L;
      entriesRead_ = 0L;
      entriesWritten_ = 0L;
      compactionAgeNanos_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.apache.accumulo.grpc.compaction.protobuf.CompactionCoordinatorServiceProto.internal_static_compaction_coordinator_PCompactionStatusUpdate_descriptor;
    }

    @java.lang.Override
    public org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate getDefaultInstanceForType() {
      return org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.getDefaultInstance();
    }

    @java.lang.Override
    public org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate build() {
      org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate buildPartial() {
      org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate result = new org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.state_ = state_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.entriesToBeCompacted_ = entriesToBeCompacted_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.entriesRead_ = entriesRead_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.entriesWritten_ = entriesWritten_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.compactionAgeNanos_ = compactionAgeNanos_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate) {
        return mergeFrom((org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate other) {
      if (other == org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate.getDefaultInstance()) return this;
      if (other.state_ != 0) {
        setStateValue(other.getStateValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getEntriesToBeCompacted() != 0L) {
        setEntriesToBeCompacted(other.getEntriesToBeCompacted());
      }
      if (other.getEntriesRead() != 0L) {
        setEntriesRead(other.getEntriesRead());
      }
      if (other.getEntriesWritten() != 0L) {
        setEntriesWritten(other.getEntriesWritten());
      }
      if (other.getCompactionAgeNanos() != 0L) {
        setCompactionAgeNanos(other.getCompactionAgeNanos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              state_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              entriesToBeCompacted_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              entriesRead_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              entriesWritten_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              compactionAgeNanos_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int state_ = 0;
    /**
     * <code>.compaction_coordinator.PCompactionState state = 1;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <code>.compaction_coordinator.PCompactionState state = 1;</code>
     * @param value The enum numeric value on the wire for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateValue(int value) {
      state_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.compaction_coordinator.PCompactionState state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public org.apache.accumulo.grpc.compaction.protobuf.PCompactionState getState() {
      org.apache.accumulo.grpc.compaction.protobuf.PCompactionState result = org.apache.accumulo.grpc.compaction.protobuf.PCompactionState.forNumber(state_);
      return result == null ? org.apache.accumulo.grpc.compaction.protobuf.PCompactionState.UNRECOGNIZED : result;
    }
    /**
     * <code>.compaction_coordinator.PCompactionState state = 1;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(org.apache.accumulo.grpc.compaction.protobuf.PCompactionState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      state_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.compaction_coordinator.PCompactionState state = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      bitField0_ = (bitField0_ & ~0x00000001);
      state_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private long entriesToBeCompacted_ ;
    /**
     * <code>int64 entriesToBeCompacted = 3;</code>
     * @return The entriesToBeCompacted.
     */
    @java.lang.Override
    public long getEntriesToBeCompacted() {
      return entriesToBeCompacted_;
    }
    /**
     * <code>int64 entriesToBeCompacted = 3;</code>
     * @param value The entriesToBeCompacted to set.
     * @return This builder for chaining.
     */
    public Builder setEntriesToBeCompacted(long value) {

      entriesToBeCompacted_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 entriesToBeCompacted = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntriesToBeCompacted() {
      bitField0_ = (bitField0_ & ~0x00000004);
      entriesToBeCompacted_ = 0L;
      onChanged();
      return this;
    }

    private long entriesRead_ ;
    /**
     * <code>int64 entriesRead = 4;</code>
     * @return The entriesRead.
     */
    @java.lang.Override
    public long getEntriesRead() {
      return entriesRead_;
    }
    /**
     * <code>int64 entriesRead = 4;</code>
     * @param value The entriesRead to set.
     * @return This builder for chaining.
     */
    public Builder setEntriesRead(long value) {

      entriesRead_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 entriesRead = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntriesRead() {
      bitField0_ = (bitField0_ & ~0x00000008);
      entriesRead_ = 0L;
      onChanged();
      return this;
    }

    private long entriesWritten_ ;
    /**
     * <code>int64 entriesWritten = 5;</code>
     * @return The entriesWritten.
     */
    @java.lang.Override
    public long getEntriesWritten() {
      return entriesWritten_;
    }
    /**
     * <code>int64 entriesWritten = 5;</code>
     * @param value The entriesWritten to set.
     * @return This builder for chaining.
     */
    public Builder setEntriesWritten(long value) {

      entriesWritten_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 entriesWritten = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntriesWritten() {
      bitField0_ = (bitField0_ & ~0x00000010);
      entriesWritten_ = 0L;
      onChanged();
      return this;
    }

    private long compactionAgeNanos_ ;
    /**
     * <code>int64 compactionAgeNanos = 6;</code>
     * @return The compactionAgeNanos.
     */
    @java.lang.Override
    public long getCompactionAgeNanos() {
      return compactionAgeNanos_;
    }
    /**
     * <code>int64 compactionAgeNanos = 6;</code>
     * @param value The compactionAgeNanos to set.
     * @return This builder for chaining.
     */
    public Builder setCompactionAgeNanos(long value) {

      compactionAgeNanos_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 compactionAgeNanos = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompactionAgeNanos() {
      bitField0_ = (bitField0_ & ~0x00000020);
      compactionAgeNanos_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:compaction_coordinator.PCompactionStatusUpdate)
  }

  // @@protoc_insertion_point(class_scope:compaction_coordinator.PCompactionStatusUpdate)
  private static final org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate();
  }

  public static org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PCompactionStatusUpdate>
      PARSER = new com.google.protobuf.AbstractParser<PCompactionStatusUpdate>() {
    @java.lang.Override
    public PCompactionStatusUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PCompactionStatusUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PCompactionStatusUpdate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.apache.accumulo.grpc.compaction.protobuf.PCompactionStatusUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

