/*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   https://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*/

"use strict";

const COLUMN_MAP = new Map([
  ["Last Contact", {"header":"Last Contact","description":"Last Contact Time","classes":"duration"}],
  ["Resource Group", {"header":"Resource Group","description":"Resource Group Name","classes":""}],
  ["Server Address", {"header":"Server Address","description":"Server Address","classes":"firstcell"}],
  ["Server Type", {"header":"Server Type","description":"Server Process Type","classes":""}],
  ["accumulo.balancer.migrations.needed", {"header":"Balancer Migrations Needed","description":"The number of migrations that need to complete before the system is balanced.","classes":"big-num"}],
  ["accumulo.blockcache.data.evictioncount", {"header":"Data Block Cache Eviction Count","description":"Data block cache eviction count.","classes":"big-num"}],
  ["accumulo.blockcache.data.hitcount", {"header":"Data Block Cache Hit Count","description":"Data block cache hit count.","classes":"big-num"}],
  ["accumulo.blockcache.data.requestcount", {"header":"Data Block Cache Request Count","description":"Data block cache request count.","classes":"big-num"}],
  ["accumulo.blockcache.index.evictioncount", {"header":"Index Block Cache Eviction Count","description":"Index block cache eviction count.","classes":"big-num"}],
  ["accumulo.blockcache.index.hitcount", {"header":"Index Block Cache Hit Count","description":"Index block cache hit count.","classes":"big-num"}],
  ["accumulo.blockcache.index.requestcount", {"header":"Index Block Cache Request Count","description":"Index block cache request count.","classes":"big-num"}],
  ["accumulo.blockcache.summary.evictioncount", {"header":"Summary Block Cache Eviction Count","description":"Summary block cache eviction count.","classes":"big-num"}],
  ["accumulo.blockcache.summary.hitcount", {"header":"Summary Block Cache Hit Count","description":"Summary block cache hit count.","classes":"big-num"}],
  ["accumulo.blockcache.summary.requestcount", {"header":"Summary Block Cache Request Count","description":"Summary block cache request count.","classes":"big-num"}],
  ["accumulo.compaction.entries.read", {"header":"Compaction Entries Read","description":"Number of entries read by all compactions that have run on this compactor (majc) or tserver (minc).","classes":"big-num"}],
  ["accumulo.compaction.entries.written", {"header":"Compaction Entries Written","description":"Number of entries written by all compactions that have run on this compactor (majc) or tserver (minc).","classes":"big-num"}],
  ["accumulo.compaction.majc.cancelled", {"header":"Majc Cancelled","description":"Number compactions that have been cancelled on this compactor","classes":"big-num"}],
  ["accumulo.compaction.majc.completed", {"header":"Majc Completed","description":"Number compactions that have succeeded on this compactor","classes":"big-num"}],
  ["accumulo.compaction.majc.failed", {"header":"Majc Failed","description":"Number compactions that have failed on this compactor","classes":"big-num"}],
  ["accumulo.compaction.majc.failures.consecutive", {"header":"Majc Consecutive Failures","description":"Number of consecutive compaction failures. Resets to zero on a successful compaction","classes":"big-num"}],
  ["accumulo.compaction.majc.in_progress", {"header":"Majc In Progress","description":"Indicator of whether a compaction is in-progress (value: 1) or not (value: 0). An in-progress compaction could also be stuck.","classes":"big-num"}],
  ["accumulo.compaction.majc.paused", {"header":"Majc Paused","description":"Number of paused major compactions.","classes":"big-num"}],
  ["accumulo.compaction.majc.stuck", {"header":"Majc Stuck","description":"Number and duration of stuck major compactions.","classes":"big-num"}],
  ["accumulo.compaction.minc.paused", {"header":"Minc Paused","description":"Number of paused minor compactions.","classes":"big-num"}],
  ["accumulo.compaction.minc.queued", {"header":"Minc Queued","description":"Queued minor compactions time queued.","classes":"big-num"}],
  ["accumulo.compaction.minc.running", {"header":"Minc Running","description":"Minor compactions time active.","classes":"big-num"}],
  ["accumulo.compaction.minc.stuck", {"header":"Minc Stuck","description":"Number and duration of stuck minor compactions.","classes":"big-num"}],
  ["accumulo.compaction.process.terminated", {"header":"Majc Consecutive Failure Termination","description":"Will report 1 if the Compactor terminates due to consecutive failures, else 0. Emitting this metric is a best effort before the process terminates","classes":"big-num"}],
  ["accumulo.compaction.queue.count", {"header":"Compaction Queue Count","description":"Number of priority queues for compaction jobs.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.avg.age", {"header":"Compaction Queue Avg Job Age","description":"Average age of currently queued jobs in seconds.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.dequeued", {"header":"Compaction Jobs Dequeued","description":"Count of dequeued jobs.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.exit.time", {"header":"Compaction Queue Job Time Queued","description":"Tracks time a job spent in the queue before exiting the queue.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.max.age", {"header":"Compaction Queue Max Job Age","description":"Maximum age of currently queued jobs in seconds.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.min.age", {"header":"Compaction Queue Min Job Age","description":"Minimum age of currently queued jobs in seconds.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.priority", {"header":"Compaction Queue Lowest Priority","description":"Lowest priority queued job.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.queued", {"header":"Compaction Jobs Queued","description":"Count of queued jobs.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.rejected", {"header":"Compaction Queue Jobs Rejected","description":"Count of rejected jobs.","classes":"big-num"}],
  ["accumulo.compaction.queue.jobs.size", {"header":"Compaction Queued Jobs Size","description":"Size of queued jobs in bytes.","classes":"big-num"}],
  ["accumulo.compaction.svc.meta.misconfigured", {"header":"Meta Compaction Svc Errors","description":"A value of 1 indicates a misconfiguration in the compaction service, while a value of 0 indicates that the configuration is valid.","classes":"big-num"}],
  ["accumulo.compaction.svc.root.misconfigured", {"header":"Root Compaction Svc Errors","description":"A value of 1 indicates a misconfiguration in the compaction service, while a value of 0 indicates that the configuration is valid.","classes":"big-num"}],
  ["accumulo.compaction.svc.user.misconfigured", {"header":"User Compaction Svc Errors","description":"A value of 1 indicates a misconfiguration in the compaction service, while a value of 0 indicates that the configuration is valid.","classes":"big-num"}],
  ["accumulo.detected.low.memory", {"header":"Low Memory","description":"Reports 1 when process memory usage is above the threshold, reports 0 when memory is okay.","classes":"memory-state"}],
  ["accumulo.fate.errors", {"header":"Fate Errors Count","description":"Count of errors that occurred when attempting to gather fate metrics.","classes":"big-num"}],
  ["accumulo.fate.ops", {"header":"Current Fate Ops Count","description":"Number of all the current FATE ops in any state.","classes":"big-num"}],
  ["accumulo.fate.ops.activity", {"header":"Total Fate Ops Count","description":"Count of the total number of times fate operations are added, updated, and removed.","classes":"big-num"}],
  ["accumulo.fate.ops.in.progress.by.type", {"header":"Fate Ops In Progess Count","description":"Number of FATE operations in progress. The op type is designated by the `op.type` tag.","classes":"big-num"}],
  ["accumulo.fate.ops.threads.inactive", {"header":"Fate Threads Inactive","description":"Keeps track of the number of idle threads (not working on a fate operation) in the thread pool. The pool name can be found in the pool.name tag. The fate instance type can be found in the instanceType tag.","classes":"big-num"}],
  ["accumulo.fate.ops.threads.total", {"header":"Fate Threads Total","description":"Keeps track of the total number of threads in the thread pool. The pool name can be found in the pool.name tag. The fate instance type can be found in the instanceType tag.","classes":"big-num"}],
  ["accumulo.fate.tx", {"header":"Fate Ops State Count","description":"Count of FATE operations in a certain state. The state is now in a tag (e.g., state\u003dnew, state\u003din.progress, state\u003dfailed, etc.).","classes":"big-num"}],
  ["accumulo.gc.candidates", {"header":"GC File Deletion Candidate Count","description":"Number of files that are candidates for deletion.","classes":"big-num"}],
  ["accumulo.gc.deleted", {"header":"GC File Candidates Deleted","description":"Number of candidate files deleted.","classes":"big-num"}],
  ["accumulo.gc.errors", {"header":"GC File Candidate Deletion Errors","description":"Number of candidate deletion errors.","classes":"big-num"}],
  ["accumulo.gc.finished", {"header":"GC File Cycle End Time","description":"Timestamp GC file collect cycle finished.","classes":"big-num"}],
  ["accumulo.gc.in.use", {"header":"GC File Deletion Candidates In Use","description":"Number of candidate files still in use.","classes":"big-num"}],
  ["accumulo.gc.post.op.duration", {"header":"GC Post Ops Duration","description":"GC metadata table post operation duration in milliseconds.","classes":"big-num"}],
  ["accumulo.gc.run.cycle", {"header":"GC Cycle Count","description":"Count of gc cycle runs. Value is reset on process start.","classes":"big-num"}],
  ["accumulo.gc.started", {"header":"GC File Cycle Start Time","description":"Timestamp GC file collection cycle started.","classes":"big-num"}],
  ["accumulo.gc.wal.candidates", {"header":"GC WAL Deletion Candidate Count","description":"Number of files that are candidates for deletion.","classes":"big-num"}],
  ["accumulo.gc.wal.deleted", {"header":"GC WAL Candidates Deleted","description":"Number of candidate wal files deleted.","classes":"big-num"}],
  ["accumulo.gc.wal.errors", {"header":"GC WAL Candidate Deletion Errors","description":"Number candidate wal file deletion errors.","classes":"big-num"}],
  ["accumulo.gc.wal.finished", {"header":"GC WAL Cycle End Time","description":"Timestamp GC WAL collect cycle finished.","classes":"big-num"}],
  ["accumulo.gc.wal.in.use", {"header":"GC WAL Deletion Candidaets In Use","description":"Number of wal file candidates that are still in use.","classes":"big-num"}],
  ["accumulo.gc.wal.started", {"header":"GC WAL Cycle Start Time","description":"Timestamp GC WAL collection cycle started.","classes":"big-num"}],
  ["accumulo.ingest.bytes", {"header":"Bytes Ingested","description":"Ingest byte count. The rate can be derived from this metric.","classes":"big-size"}],
  ["accumulo.ingest.entries", {"header":"Entries Ingested","description":"Ingest entry (a key/value) count. The rate can be derived from this metric.","classes":"big-num"}],
  ["accumulo.ingest.hold", {"header":"Ingest Commit Hold Time","description":"Duration for which commits have been held in milliseconds.","classes":"big-num"}],
  ["accumulo.manager.goal.state", {"header":"Manager Goal State","description":"Manager goal state: -1\u003dunknown, 0\u003dCLEAN_STOP, 1\u003dSAFE_MODE, 2\u003dNORMAL.","classes":"big-num"}],
  ["accumulo.minc.queued", {"header":"Minc Queued","description":"Number of queued minor compactions.","classes":"big-num"}],
  ["accumulo.minc.running", {"header":"Minc Running","description":"Number of active minor compactions.","classes":"big-num"}],
  ["accumulo.minc.total", {"header":"Minc Completed","description":"Total number of minor compactions performed.","classes":"big-num"}],
  ["accumulo.recoveries.avg.progress", {"header":"Tablet Recovery Avg Percent Complete","description":"The average percentage (0.0 - 99.9) of the in progress recoveries.","classes":"big-num"}],
  ["accumulo.recoveries.in.progress", {"header":"Tablet Recoveries In Progress","description":"The number of recoveries in progress.","classes":"big-num"}],
  ["accumulo.recoveries.runtime.longest", {"header":"Tablet Recovery Longest Time","description":"The time (in milliseconds) of the longest running recovery.","classes":"big-num"}],
  ["accumulo.scan.busy.timeout.count", {"header":"Scan Busy Count","description":"Count of the scans where a busy timeout happened.","classes":"big-num"}],
  ["accumulo.scan.close", {"header":"Scan Close Count","description":"Number of calls to close a scan or multiscan.","classes":"big-num"}],
  ["accumulo.scan.continue", {"header":"Scan Continue Count","description":"Number of calls to continue a scan or multiscan.","classes":"big-num"}],
  ["accumulo.scan.files.open", {"header":"Scan Files Open","description":"Number of files open for scans.","classes":"big-num"}],
  ["accumulo.scan.paused.for.memory", {"header":"Scans Paused For Low Memory","description":"Count of scans paused due to server being low on memory.","classes":"big-num"}],
  ["accumulo.scan.queries", {"header":"Tablet Lookup Count","description":"Number of queries made during scans.","classes":"big-num"}],
  ["accumulo.scan.query.results", {"header":"Returned Entry Count","description":"Query count. The rate can be derived from this metric.","classes":"big-num"}],
  ["accumulo.scan.query.results.bytes", {"header":"Returned Bytes Count","description":"Query byte count. The rate can be derived from this metric.","classes":"big-size"}],
  ["accumulo.scan.query.scanned.entries", {"header":"Scanned Entry Count","description":"Count of scanned entries. The rate can be derived from this metric.","classes":"big-num"}],
  ["accumulo.scan.reservation.conflict.count", {"header":"Scan Reservation Conflicts","description":"Count of instances where file reservation attempts for scans encountered conflicts.","classes":"big-num"}],
  ["accumulo.scan.reservation.total.timer", {"header":"Scan Reservation Total Time","description":"Time to reserve a tablet\u0027s files for scan.","classes":"big-num"}],
  ["accumulo.scan.reservation.writeout.timer", {"header":"Scan Reservation Write Time","description":"Time to write out a tablets file reservations for scan.","classes":"big-num"}],
  ["accumulo.scan.result", {"header":"Scan Result Count","description":"Results per scan.","classes":"big-num"}],
  ["accumulo.scan.return.early.for.memory", {"header":"Scans Returned Early For Low Memory","description":"Count of scans that returned results early due to server being low on memory.","classes":"big-num"}],
  ["accumulo.scan.start", {"header":"Scan Start Count","description":"Number of calls to start a scan or multiscan.","classes":"big-num"}],
  ["accumulo.scan.tablet.metadata.cache", {"header":"Scan Server Tablet Cache","description":"Scan server tablet cache metrics.","classes":"big-num"}],
  ["accumulo.scan.times", {"header":"Scan Session Total Time","description":"Scan session lifetime (creation to close).","classes":"big-num"}],
  ["accumulo.scan.yields", {"header":"Scan Yield Count","description":"Counts scans that have yielded.","classes":"big-num"}],
  ["accumulo.scan.zombie.threads", {"header":"Scan Zombie Thread Count","description":"Number of scan threads that have no associated client session.","classes":"big-num"}],
  ["accumulo.server.idle", {"header":"Server Idle","description":"Indicates if the server is idle or not. The value will be 1 when idle and 0 when not idle.","classes":"idle-state"}],
  ["accumulo.tabletmgmt.meta.errors", {"header":"Meta Tablet Watcher Errors","description":"Error count encountered by the TabletGroupWatcher for the META data level.","classes":"big-num"}],
  ["accumulo.tabletmgmt.root.errors", {"header":"Root Tablet Watcher Errors","description":"Error count encountered by the TabletGroupWatcher for the ROOT data level.","classes":"big-num"}],
  ["accumulo.tabletmgmt.user.errors", {"header":"User Tablet Watcher Errors","description":"Error count encountered by the TabletGroupWatcher for the USER data level.","classes":"big-num"}],
  ["accumulo.tablets.assignments.warning", {"header":"Tablet Assignments Overdue","description":"Number of tablet assignments that are taking longer than the configured warning duration.","classes":"big-num"}],
  ["accumulo.tablets.files", {"header":"Tablet File Avg","description":"Number of files per tablet.","classes":"big-num"}],
  ["accumulo.tablets.ondemand.online", {"header":"Online On-Demand Tablets","description":"Number of online on-demand tablets","classes":"big-num"}],
  ["accumulo.tablets.ondemand.unloaded.lowmem", {"header":"On-Demand Tablets Unloaded For Memory","description":"Number of online on-demand tablets unloaded due to low memory","classes":"big-num"}],
  ["accumulo.tablets.online", {"header":"Tablets Online","description":"Number of online tablets.","classes":"big-num"}],
  ["accumulo.tablets.opening", {"header":"Tablets Opening","description":"Number of opening tablets.","classes":"big-num"}],
  ["accumulo.tablets.unopened", {"header":"Tablets Unopened","description":"Number of unopened tablets.","classes":"big-num"}],
  ["accumulo.thrift.execute", {"header":"Thrift Execution Time","description":"Time to execute an RPC request.","classes":"big-num"}],
  ["accumulo.thrift.idle", {"header":"Thrift Idle Time","description":"Time waiting to execute an RPC request.","classes":"big-num"}],
  ["accumulo.tserver.entries", {"header":"Entries Assigned","description":"Number of entries assigned to a TabletServer.","classes":"big-num"}],
  ["accumulo.tserver.entries.mem", {"header":"Entries In Memory","description":"Number of entries in memory.","classes":"big-num"}],
  ["accumulo.updates.check", {"header":"Conditional Mutation Condition Check Time","description":"Average time taken for conditional mutation to check conditions.","classes":"big-num"}],
  ["accumulo.updates.commit", {"header":"Mutation Commit Avg Total Time","description":"Average time taken to commit a mutation.","classes":"big-num"}],
  ["accumulo.updates.commit.prep", {"header":"Mutation Commit Avg Prep Time","description":"Average time taken to prepare to commit a single mutation.","classes":"big-num"}],
  ["accumulo.updates.error", {"header":"Ingest Errors","description":"Count of errors during tablet updates. Type/reason for error is stored in the `type` tag (e.g., type\u003dpermission, type\u003dunknown.tablet, type\u003dconstraint.violation).","classes":"big-num"}],
  ["accumulo.updates.lock", {"header":"Conditional Mutation Row Lock Wait Time","description":"Average time taken for conditional mutation to get a row lock.","classes":"big-num"}],
  ["accumulo.updates.mutation.arrays.size", {"header":"Mutation Batch Size","description":"Batch size of mutations from client.","classes":"big-num"}],
  ["accumulo.updates.walog.write", {"header":"WAL Write Time","description":"Time taken to write a batch of mutations to WAL.","classes":"big-num"}]
]);

