/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TermWeight.proto

package org.apache.accumulo.examples.wikisearch.protobuf;

public final class TermWeight {
  private TermWeight() {}
  
  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {}
  
  public static final class Info extends com.google.protobuf.GeneratedMessage {
    // Use Info.newBuilder() to construct.
    private Info() {
      initFields();
    }
    
    private Info(boolean noInit) {}
    
    private static final Info defaultInstance;
    
    public static Info getDefaultInstance() {
      return defaultInstance;
    }
    
    public Info getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_protobuf_Info_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internal_static_protobuf_Info_fieldAccessorTable;
    }
    
    // required float normalizedTermFrequency = 1;
    public static final int NORMALIZEDTERMFREQUENCY_FIELD_NUMBER = 1;
    private boolean hasNormalizedTermFrequency;
    private float normalizedTermFrequency_ = 0F;
    
    public boolean hasNormalizedTermFrequency() {
      return hasNormalizedTermFrequency;
    }
    
    public float getNormalizedTermFrequency() {
      return normalizedTermFrequency_;
    }
    
    // repeated uint32 wordOffset = 2;
    public static final int WORDOFFSET_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> wordOffset_ = java.util.Collections.emptyList();
    
    public java.util.List<java.lang.Integer> getWordOffsetList() {
      return wordOffset_;
    }
    
    public int getWordOffsetCount() {
      return wordOffset_.size();
    }
    
    public int getWordOffset(int index) {
      return wordOffset_.get(index);
    }
    
    private void initFields() {}
    
    public final boolean isInitialized() {
      if (!hasNormalizedTermFrequency)
        return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      getSerializedSize();
      if (hasNormalizedTermFrequency()) {
        output.writeFloat(1, getNormalizedTermFrequency());
      }
      for (int element : getWordOffsetList()) {
        output.writeUInt32(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1)
        return size;
      
      size = 0;
      if (hasNormalizedTermFrequency()) {
        size += com.google.protobuf.CodedOutputStream.computeFloatSize(1, getNormalizedTermFrequency());
      }
      {
        int dataSize = 0;
        for (int element : getWordOffsetList()) {
          dataSize += com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getWordOffsetList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(com.google.protobuf.ByteString data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(java.io.InputStream input) throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseDelimitedFrom(java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    
    public static org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info parseFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry).buildParsed();
    }
    
    public static Builder newBuilder() {
      return Builder.create();
    }
    
    public Builder newBuilderForType() {
      return newBuilder();
    }
    
    public static Builder newBuilder(org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    
    public Builder toBuilder() {
      return newBuilder(this);
    }
    
    public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info result;
      
      // Construct using protobuf.TermWeight.Info.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info();
        return builder;
      }
      
      protected org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException("Cannot call clear() after build().");
        }
        result = new org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.getDescriptor();
      }
      
      public org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info getDefaultInstanceForType() {
        return org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      
      public org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info buildParsed() throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info buildPartial() {
        if (result == null) {
          throw new IllegalStateException("build() has already been called on this Builder.");
        }
        if (result.wordOffset_ != java.util.Collections.EMPTY_LIST) {
          result.wordOffset_ = java.util.Collections.unmodifiableList(result.wordOffset_);
        }
        org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info) {
          return mergeFrom((org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info other) {
        if (other == org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.getDefaultInstance())
          return this;
        if (other.hasNormalizedTermFrequency()) {
          setNormalizedTermFrequency(other.getNormalizedTermFrequency());
        }
        if (!other.wordOffset_.isEmpty()) {
          if (result.wordOffset_.isEmpty()) {
            result.wordOffset_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.wordOffset_.addAll(other.wordOffset_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(com.google.protobuf.CodedInputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet.newBuilder(this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 13: {
              setNormalizedTermFrequency(input.readFloat());
              break;
            }
            case 16: {
              addWordOffset(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addWordOffset(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      // required float normalizedTermFrequency = 1;
      public boolean hasNormalizedTermFrequency() {
        return result.hasNormalizedTermFrequency();
      }
      
      public float getNormalizedTermFrequency() {
        return result.getNormalizedTermFrequency();
      }
      
      public Builder setNormalizedTermFrequency(float value) {
        result.hasNormalizedTermFrequency = true;
        result.normalizedTermFrequency_ = value;
        return this;
      }
      
      public Builder clearNormalizedTermFrequency() {
        result.hasNormalizedTermFrequency = false;
        result.normalizedTermFrequency_ = 0F;
        return this;
      }
      
      // repeated uint32 wordOffset = 2;
      public java.util.List<java.lang.Integer> getWordOffsetList() {
        return java.util.Collections.unmodifiableList(result.wordOffset_);
      }
      
      public int getWordOffsetCount() {
        return result.getWordOffsetCount();
      }
      
      public int getWordOffset(int index) {
        return result.getWordOffset(index);
      }
      
      public Builder setWordOffset(int index, int value) {
        result.wordOffset_.set(index, value);
        return this;
      }
      
      public Builder addWordOffset(int value) {
        if (result.wordOffset_.isEmpty()) {
          result.wordOffset_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.wordOffset_.add(value);
        return this;
      }
      
      public Builder addAllWordOffset(java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.wordOffset_.isEmpty()) {
          result.wordOffset_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.wordOffset_);
        return this;
      }
      
      public Builder clearWordOffset() {
        result.wordOffset_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Info)
    }
    
    static {
      defaultInstance = new Info(true);
      org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Info)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor internal_static_protobuf_Info_descriptor;
  private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_protobuf_Info_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }
  
  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {"\n\020TermWeight.proto\022\010protobuf\";\n\004Info\022\037\n\027"
        + "normalizedTermFrequency\030\001 \002(\002\022\022\n\nwordOff" + "set\030\002 \003(\rB\014\n\010protobufH\001"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
      public com.google.protobuf.ExtensionRegistry assignDescriptors(com.google.protobuf.Descriptors.FileDescriptor root) {
        descriptor = root;
        internal_static_protobuf_Info_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_protobuf_Info_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
            internal_static_protobuf_Info_descriptor, new java.lang.String[] {"NormalizedTermFrequency", "WordOffset",}, org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.class,
            org.apache.accumulo.examples.wikisearch.protobuf.TermWeight.Info.Builder.class);
        return null;
      }
    };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {},
        assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
